### ISSUE TITLE
Doesn't work on macOS.

### ISSUE THREAD

**Issue by ravern** [kustomzone/zerochess#1]
Does this work on macOS? Has it been tested? It seems to include a windows dependency.

**Comment by kustomzone** [comment]
I may have left Sqlite3 in there ready for saving games (currently not using) and that's compiled on Win7.
Can try leaving it out if that's causing it.
Or if needed, can try re-building Sqlite3 from source. ( https://github.com/mapbox/node-sqlite3 )

Currently testing on windows. Unable to test Mac. (none available)
